### ISSUE TITLE
Use RHYTHM instead of MEDIAN BEAT?

### ISSUE THREAD

**Issue by arturojain** [ArturRod/ecg-dicom-web-viewer#4]
**Describe the solution you'd like**
Is there a reason to use MEDIAN BEAT instead of RHYTHM or an option to choose between this should be implemented?

**Additional context**
Example study: https://we.tl/t-kKSg85j2bJ

**Comment by ArturRod** [comment]
Hi @arturojain,
I do not know the difference between MEDIAN BEAT and RHYTHM, I will have to investigate it, from what I see in the example, the data aVL and aVR arrive first empty and then with data, drawing it 2 times, and I also observe that from V3 to V6 no data arrives. Is this always the case with this format? I think you could put a button to change the format if it always has this form. Even so, do you know if there is any TAG in the DICOM indicating if it is MEDIAN BEAT or if it is RHYTHM ? How should it be displayed in RHYTHM form?
Would this be the correct way to display in RHYTHM? https://www.researchgate.net/figure/ECG-showing-sinus-rhythm-heart-rate-67-bpm-first-degree-atrioventricular-block-low_fig1_301773769
Or the 4 repeats that should occur to display V3 through v6?
![image](https://user-images.githubusercontent.com/86238895/189882127-841869a1-63b4-43b5-b936-125fac65cf2a.png)

**Comment by ArturRod** [comment]
@arturojain Fixed with the last update, v2.0.4
