### ISSUE TITLE
Installation failing

### ISSUE THREAD

**Issue by nesmeg** [ArturRod/ecg-dicom-web-viewer#5]
I added 
`    "@ohif/extension-dicom-ecg": "^1.0.3"` to the package.json as specified
and `OHIFDicomECGExtension` to the default extensions as well as `import OHIFDicomECGExtension from '@ohif/extension-dicom-ecg'` to index.js

However when running `yarn run build ` or `yarn run dev` I get this error

<img width="971" alt="image" src="https://user-images.githubusercontent.com/72559471/205520297-e2361d9e-f780-4fcd-8444-6c61c9b0a6fe.png">

**Comment by nesmeg** [comment]
This was done with the [v3-stable branch of the OHIF-viewer](https://github.com/OHIF/Viewers/tree/v3-stable)

**Comment by nesmeg** [comment]
This was done with the [v3-stable branch of the OHIF viewer](https://github.com/OHIF/Viewers/tree/v3-stable]

**Comment by nesmeg** [comment]
This issue was opened in the wrong repo and moved to the correct one.

https://github.com/ArturRod/dicom-ecg/issues/6

**Comment by ArturRod** [comment]
Hi, you can try the latest version, which is 1.0.6, since the versions have to match, since I see that it is giving error in the node packages, try version 1.0.6, which is the latest.  Anyway this is for ohif V2, I'm preparing an extension for V3 in the future.
