### ISSUE TITLE
Attached DICOM cannot be loaded.

### ISSUE THREAD

**Issue by arturojain** [ArturRod/ecg-dicom-web-viewer#9]
**Describe the bug**
This DICOM is not being loaded. An error is produced when trying to load it.

**To Reproduce**
Load the DICOM.

**Expected behavior**
It should show the DICOM.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version 114.0.5735.133 (Official Build) (arm64)

**Additional context**
DICOM: https://we.tl/t-PAAYpQPkd5

If the DICOM has bad data it could be ignored or alerted, but just failing might not be the optimal way.

**Comment by ArturRod** [comment]
Hi @arturojain, the error has been fixed with version 2.0.8
